### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ghost** [dfgHiatus/neosTextToSpeech#1]
```
NeosTTS (Text To Speech) by dfgHiatus.

When audio is generated, you'll see a message that is was and where it's stored.
As long as this window stays open, this should run with no issues.
KNOWN ISSUES: Bad queries can cause this to crash, *you have been warned.*

[Info] Websocket created on port 7000.

Error in connection handler
Traceback (most recent call last):
  File "websockets\server.py", line 191, in handler
  File "neosTTS.py", line 55, in facetrack
  File "subprocess.py", line 340, in call
  File "subprocess.py", line 854, in __init__
  File "subprocess.py", line 1307, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by ghost** [comment]
This happens as soon as I hit synthesize
